In [ ]:
import requests
import json
import pandas as pd

In [ ]:
url = "https://jobsearch.api.jobtechdev.se/search"

params = {
    "q": "data analyst",
    "offset": 0,
    "limit": 10
}

response = requests.get(url, params=params)

print(response.status_code)

200

In [ ]:
data = response.json()

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['total', 'positions', 'query_time_in_millis', 'result_time_in_millis', 'stats', 'freetext_concepts', 'hits'])

In [ ]:
jobs = data["hits"]

print(type(jobs))
print(len(jobs))

<class 'list'>
10

In [ ]:
first_job = jobs[0]

print(first_job.keys())

dict_keys(['relevance', 'id', 'external_id', 'original_id', 'label', 'webpage_url', 'logo_url', 'headline', 'application_deadline', 'number_of_vacancies', 'description', 'employment_type', 'salary_type', 'salary_description', 'duration', 'working_hours_type', 'scope_of_work', 'access', 'employer', 'application_details', 'experience_required', 'access_to_own_car', 'driving_license_required', 'driving_license', 'occupation', 'occupation_group', 'occupation_field', 'workplace_model', 'workplace_address', 'workplace_addresses', 'must_have', 'nice_to_have', 'application_contacts', 'publication_date', 'last_publication_date', 'removed', 'removed_date', 'source_type', 'timestamp'])

In [ ]:
print("Job ID:", first_job["id"])
print("Headline:", first_job["headline"])
print("Vacancies:", first_job["number_of_vacancies"])
print("Employer:", first_job["employer"]["name"])
print("Occupation:", first_job["occupation"]["label"])
print("Municipality:", first_job["workplace_address"]["municipality"])
print("Region:", first_job["workplace_address"]["region"])
print("Published:", first_job["publication_date"])
print("Deadline:", first_job["application_deadline"])

Job ID: 31480654
Headline: Data Analyst
Vacancies: 1
Employer: Siemens Energy AB
Occupation: Dataanalytiker
Municipality: Finspång
Region: Östergötlands län
Published: 2026-09-15T15:50:08
Deadline: 2026-10-15T23:59:59

In [ ]:
df = pd.json_normalize(jobs)

print(df.shape)

(10, 90)

In [ ]:
df.head()

,relevance,id,external_id,original_id,label,webpage_url,logo_url,headline,application_deadline,number_of_vacancies,...,must_have.skills,must_have.languages,must_have.work_experiences,must_have.education,must_have.education_level,nice_to_have.skills,nice_to_have.languages,nice_to_have.work_experiences,nice_to_have.education,nice_to_have.education_level
0,1.00000,31480654,None,None,[],https://arbetsformedlingen.se/platsbanken/anno...,https://arbetsformedlingen.se/rest/employer-lo...,Data Analyst,2026-10-15T23:59:59,1,...,[],[],"[{'weight': 10, 'concept_id': 'eTVL_hfE_Lyh', ...",[],[],[],[],[],[],[]
1,1.00000,31471972,None,None,[],https://arbetsformedlingen.se/platsbanken/anno...,https://arbetsformedlingen.se/rest/employer-lo...,Data Analyst,2026-10-04T23:59:59,1,...,[],[],[],[],[],[],[],[],[],[]
2,0.95826,31548327,None,None,[],https://arbetsformedlingen.se/platsbanken/anno...,https://arbetsformedlingen.se/rest/employer-lo...,Data Analyst Intern,2026-10-12T23:59:59,1,...,[],[],[],[],[],[],[],"[{'weight': 5, 'concept_id': 'eTVL_hfE_Lyh', '...",[],[]
3,0.95826,31518608,None,None,[],https://arbetsformedlingen.se/platsbanken/anno...,https://arbetsformedlingen.se/rest/employer-lo...,Senior Data Analyst,2026-10-25T23:59:59,1,...,[],"[{'weight': 10, 'concept_id': 'NVxJ_hLg_TYS', ...","[{'weight': 10, 'concept_id': 'eTVL_hfE_Lyh', ...",[],[],[],[],[],[],[]
4,0.95826,31480658,None,None,[],https://arbetsformedlingen.se/platsbanken/anno...,https://arbetsformedlingen.se/rest/employer-lo...,(Senior) Data Analyst,2026-10-15T23:59:59,1,...,[],[],"[{'weight': 10, 'concept_id': 'eTVL_hfE_Lyh', ...",[],[],[],[],[],[],[]

In [ ]:
for column in df.columns:
    print(column)

relevance
id
external_id
original_id
label
webpage_url
logo_url
headline
application_deadline
number_of_vacancies
salary_description
access
experience_required
access_to_own_car
driving_license_required
driving_license
workplace_addresses
application_contacts
publication_date
last_publication_date
removed
removed_date
source_type
timestamp
description.text
description.text_formatted
description.company_information
description.needs
description.requirements
description.conditions
employment_type.concept_id
employment_type.label
employment_type.legacy_ams_taxonomy_id
salary_type.concept_id
salary_type.label
salary_type.legacy_ams_taxonomy_id
duration.concept_id
duration.label
duration.legacy_ams_taxonomy_id
working_hours_type.concept_id
working_hours_type.label
working_hours_type.legacy_ams_taxonomy_id
scope_of_work.min
scope_of_work.max
employer.phone_number
employer.email
employer.url
employer.organization_number
employer.name
employer.workplace
application_details.information
application_details.reference
application_details.email
application_details.via_af
application_details.url
application_details.other
occupation.concept_id
occupation.label
occupation.legacy_ams_taxonomy_id
occupation_group.concept_id
occupation_group.label
occupation_group.legacy_ams_taxonomy_id
occupation_field.concept_id
occupation_field.label
occupation_field.legacy_ams_taxonomy_id
workplace_model.concept_id
workplace_model.label
workplace_address.municipality
workplace_address.municipality_code
workplace_address.municipality_concept_id
workplace_address.region
workplace_address.region_code
workplace_address.region_concept_id
workplace_address.country
workplace_address.country_code
workplace_address.country_concept_id
workplace_address.street_address
workplace_address.postcode
workplace_address.city
workplace_address.coordinates
must_have.skills
must_have.languages
must_have.work_experiences
must_have.education
must_have.education_level
nice_to_have.skills
nice_to_have.languages
nice_to_have.work_experiences
nice_to_have.education
nice_to_have.education_level

In [ ]:
profile_columns = [
    "id",
    "headline",
    "number_of_vacancies",
    "publication_date",
    "application_deadline",
    "experience_required",

    "employer.organization_number",
    "employer.name",

    "occupation.concept_id",
    "occupation.label",
    "occupation_group.label",
    "occupation_field.label",

    "employment_type.label",
    "duration.label",
    "working_hours_type.label",
    "scope_of_work.min",
    "scope_of_work.max",

    "workplace_address.municipality",
    "workplace_address.municipality_code",
    "workplace_address.region",
    "workplace_address.region_code",
    "workplace_address.country",

    "workplace_model.label"
]

df_profile = df[profile_columns]

df_profile.head()

,id,headline,number_of_vacancies,publication_date,application_deadline,experience_required,employer.organization_number,employer.name,occupation.concept_id,occupation.label,...,duration.label,working_hours_type.label,scope_of_work.min,scope_of_work.max,workplace_address.municipality,workplace_address.municipality_code,workplace_address.region,workplace_address.region_code,workplace_address.country,workplace_model.label
0,31480654,Data Analyst,1,2026-09-15T15:50:08,2026-10-15T23:59:59,True,5566066048,Siemens Energy AB,eTVL_hfE_Lyh,Dataanalytiker,...,Tills vidare,Heltid,100,100,Finspång,0562,Östergötlands län,05,Sverige,None
1,31471972,Data Analyst,1,2026-09-14T10:05:12,2026-10-04T23:59:59,True,5566746250,Essiq AB,eTVL_hfE_Lyh,Dataanalytiker,...,Tills vidare,Heltid,100,100,Göteborg,1480,Västra Götalands län,14,Sverige,None
2,31548327,Data Analyst Intern,1,2026-10-02T14:58:36,2026-10-12T23:59:59,False,5568873763,Rovio Sweden AB,eTVL_hfE_Lyh,Dataanalytiker,...,6 månader – upp till 12 månader,Heltid,100,100,Stockholm,0180,Stockholms län,01,Sverige,None
3,31518608,Senior Data Analyst,1,2026-09-25T07:40:55,2026-10-25T23:59:59,True,5569468498,Acast AB (publ),eTVL_hfE_Lyh,Dataanalytiker,...,Tills vidare,Heltid,100,100,Stockholm,0180,Stockholms län,01,Sverige,None
4,31480658,(Senior) Data Analyst,1,2026-09-15T15:50:10,2026-10-15T23:59:59,True,5566066048,Siemens Energy AB,eTVL_hfE_Lyh,Dataanalytiker,...,Tills vidare,Heltid,100,100,Finspång,0562,Östergötlands län,05,Sverige,None

In [ ]:
df_profile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   id                                   10 non-null     object
 1   headline                             10 non-null     object
 2   number_of_vacancies                  10 non-null     int64
 3   publication_date                     10 non-null     object
 4   application_deadline                 10 non-null     object
 5   experience_required                  10 non-null     bool
 6   employer.organization_number         10 non-null     object
 7   employer.name                        10 non-null     object
 8   occupation.concept_id                10 non-null     object
 9   occupation.label                     10 non-null     object
 10  occupation_group.label               10 non-null     object
 11  occupation_field.label               10 non-null     object
 12  employment_type.label                10 non-null     object
 13  duration.label                       10 non-null     object
 14  working_hours_type.label             10 non-null     object
 15  scope_of_work.min                    10 non-null     int64
 16  scope_of_work.max                    10 non-null     int64
 17  workplace_address.municipality       10 non-null     object
 18  workplace_address.municipality_code  10 non-null     object
 19  workplace_address.region             10 non-null     object
 20  workplace_address.region_code        10 non-null     object
 21  workplace_address.country            10 non-null     object
 22  workplace_model.label                0 non-null      object
dtypes: bool(1), int64(3), object(19)
memory usage: 1.9+ KB

In [ ]:
missing_profile = pd.DataFrame({
    "Missing_Count": df_profile.isnull().sum(),
    "Missing_Percent": (df_profile.isnull().sum() / len(df_profile) * 100).round(1)
})

missing_profile

                                     Missing_Count  Missing_Percent
id                                               0              0.0
headline                                         0              0.0
number_of_vacancies                              0              0.0
publication_date                                 0              0.0
application_deadline                             0              0.0
experience_required                              0              0.0
employer.organization_number                     0              0.0
employer.name                                    0              0.0
occupation.concept_id                            0              0.0
occupation.label                                 0              0.0
occupation_group.label                           0              0.0
occupation_field.label                           0              0.0
employment_type.label                            0              0.0
duration.label                                   0              0.0
working_hours_type.label                         0              0.0
scope_of_work.min                                0              0.0
scope_of_work.max                                0              0.0
workplace_address.municipality                   0              0.0
workplace_address.municipality_code              0              0.0
workplace_address.region                         0              0.0
workplace_address.region_code                    0              0.0
workplace_address.country                        0              0.0
workplace_model.label                           10            100.0

In [ ]:
duplicate_ids = df_profile["id"].duplicated().sum()

print("Duplicate Job IDs:", duplicate_ids)
print("Unique Job IDs:", df_profile["id"].nunique())
print("Total Rows:", len(df_profile))

Duplicate Job IDs: 0
Unique Job IDs: 10
Total Rows: 10

In [ ]:
print("Total matching jobs:", data["total"]["value"])
print("Jobs returned in this request:", len(data["hits"]))

Total matching jobs: 14
Jobs returned in this request: 10

In [ ]:
url = "https://jobsearch.api.jobtechdev.se/search"

params_all = {
    "offset": 0,
    "limit": 10
}

response_all = requests.get(url, params=params_all)
response_all.raise_for_status()

data_all = response_all.json()

print("Status:", response_all.status_code)
print("Total available jobs:", data_all["total"]["value"])
print("Jobs returned:", len(data_all["hits"]))

Status: 200
Total available jobs: 41213
Jobs returned: 10

In [ ]:
test_params = {
    "offset": 0,
    "limit": 100
}

test_response = requests.get(url, params=test_params)
test_response.raise_for_status()

test_data = test_response.json()

print("Status:", test_response.status_code)
print("Total available:", test_data["total"]["value"])
print("Requested:", 100)
print("Actually returned:", len(test_data["hits"]))

Status: 200
Total available: 41213
Requested: 100
Actually returned: 100

In [ ]:
all_jobs = []

batch_size = 100
target_jobs = 500

for offset in range(0, target_jobs, batch_size):

    params = {
        "offset": offset,
        "limit": batch_size
    }

    response = requests.get(url, params=params)
    response.raise_for_status()

    batch_data = response.json()
    jobs_batch = batch_data["hits"]

    all_jobs.extend(jobs_batch)

    print(
        f"Offset: {offset} | "
        f"Retrieved: {len(jobs_batch)} | "
        f"Total collected: {len(all_jobs)}"
    )

print("\nFinal number of jobs collected:", len(all_jobs))

Offset: 0 | Retrieved: 100 | Total collected: 100
Offset: 100 | Retrieved: 100 | Total collected: 200
Offset: 200 | Retrieved: 100 | Total collected: 300
Offset: 300 | Retrieved: 100 | Total collected: 400
Offset: 400 | Retrieved: 100 | Total collected: 500

Final number of jobs collected: 500

In [ ]:
# Extract the job IDs from all 500 records
job_ids = [job["id"] for job in all_jobs]

print("Total records:", len(job_ids))
print("Unique Job IDs:", len(set(job_ids)))
print("Duplicate Job IDs:", len(job_ids) - len(set(job_ids)))

Total records: 500
Unique Job IDs: 500
Duplicate Job IDs: 0

In [ ]:
from datetime import datetime

extract_date = datetime.now().strftime("%Y%m%d_%H%M%S")
raw_filename = f"job_ads_raw_{extract_date}.json"

with open(raw_filename, "w", encoding="utf-8") as f:
    json.dump(all_jobs, f, ensure_ascii=False, indent=2)

print("Raw file saved:", raw_filename)
print("Records saved:", len(all_jobs))

Raw file saved: job_ads_raw_20261002_192419.json
Records saved: 500

In [ ]:
df_all = pd.json_normalize(all_jobs)

print("Rows:", df_all.shape[0])
print("Columns:", df_all.shape[1])

Rows: 500
Columns: 90

In [ ]:
complex_columns = []

for column in df_all.columns:
    has_complex = df_all[column].apply(
        lambda x: isinstance(x, (list, dict))
    ).any()

    if has_complex:
        complex_columns.append(column)

print("Number of columns containing lists/dictionaries:", len(complex_columns))

for column in complex_columns:
    print(column)

Number of columns containing lists/dictionaries: 15
label
driving_license
workplace_addresses
application_contacts
workplace_address.coordinates
must_have.skills
must_have.languages
must_have.work_experiences
must_have.education
must_have.education_level
nice_to_have.skills
nice_to_have.languages
nice_to_have.work_experiences
nice_to_have.education
nice_to_have.education_level

In [ ]:
skills_example = df_all[
    df_all["must_have.skills"].apply(
        lambda x: isinstance(x, list) and len(x) > 0
    )
][["id", "headline", "must_have.skills"]]

print("Jobs with must-have skills:", len(skills_example))

skills_example.head(5)

Jobs with must-have skills: 13

,id,headline,must_have.skills
31,31549567,Helgbagare sökes - Robin Delselius Bageri,"[{'weight': None, 'concept_id': 'btqh_hCy_bRi'..."
99,31549412,HR-partner med inriktning arbetsmiljö och reha...,"[{'weight': None, 'concept_id': 'pmgB_Pvx_9fK'..."
129,31549325,Handläggare/Utredare | Offentlig verksamhet | ...,"[{'weight': None, 'concept_id': 'QAaJ_QeY_Q6P'..."
143,31549258,Är du en skicklig och positiv vvs montör?,"[{'weight': None, 'concept_id': 'DaGA_bsf_rVQ'..."
152,31549198,Är du en skicklig och positiv vvs montör?,"[{'weight': None, 'concept_id': '9QkV_AAn_M1g'..."

In [ ]:
# Remove columns containing lists/dictionaries from the main staging dataset
staging_columns = [
    col for col in df_all.columns
    if col not in complex_columns
]

df_staging = df_all[staging_columns].copy()

print("Original columns:", df_all.shape[1])
print("Complex columns excluded:", len(complex_columns))
print("Staging columns:", df_staging.shape[1])
print("Staging rows:", df_staging.shape[0])

Original columns: 90
Complex columns excluded: 15
Staging columns: 75
Staging rows: 500

In [ ]:
job_skills = []

for job in all_jobs:
    job_id = job["id"]

    for skill in job["must_have"]["skills"]:
        job_skills.append({
            "job_id": job_id,
            "skill_concept_id": skill.get("concept_id"),
            "skill_label": skill.get("label"),
            "skill_weight": skill.get("weight")
        })

df_job_skills = pd.DataFrame(job_skills)

print("Skill requirement rows:", len(df_job_skills))
print("Jobs represented:", df_job_skills["job_id"].nunique())

df_job_skills.head(10)

Skill requirement rows: 16
Jobs represented: 13

     job_id skill_concept_id                     skill_label skill_weight
0  31549567     btqh_hCy_bRi                    Bageriarbete         None
1  31549412     pmgB_Pvx_9fK  Rehabilitering, personalarbete         None
2  31549325     QAaJ_QeY_Q6P                  Utredningsvana         None
3  31549258     DaGA_bsf_rVQ    Utbildningsbevis, VVS-montör         None
4  31549258     9QkV_AAn_M1g  Utbildningsbevis, säker vatten         None
5  31549198     9QkV_AAn_M1g  Utbildningsbevis, säker vatten         None
6  31549198     DaGA_bsf_rVQ    Utbildningsbevis, VVS-montör         None
7  31548985     Tpvt_9yv_KAw           Taxiförarlegitimation         None
8  31548939     TGZ1_Xb5_77h                        Elteknik         None
9  31548890     Betk_ZCh_mY9              Personalutveckling         None

In [ ]:
requirement_columns = [
    "must_have.skills",
    "must_have.languages",
    "must_have.work_experiences",
    "must_have.education",
    "must_have.education_level",
    "nice_to_have.skills",
    "nice_to_have.languages",
    "nice_to_have.work_experiences",
    "nice_to_have.education",
    "nice_to_have.education_level"
]

for column in requirement_columns:
    jobs_with_values = df_all[column].apply(
        lambda x: isinstance(x, list) and len(x) > 0
    ).sum()

    print(f"{column}: {jobs_with_values} jobs")

must_have.skills: 13 jobs
must_have.languages: 62 jobs
must_have.work_experiences: 35 jobs
must_have.education: 11 jobs
must_have.education_level: 11 jobs
nice_to_have.skills: 14 jobs
nice_to_have.languages: 25 jobs
nice_to_have.work_experiences: 97 jobs
nice_to_have.education: 12 jobs
nice_to_have.education_level: 12 jobs

In [ ]:
fields_to_inspect = [
    "must_have.languages",
    "must_have.work_experiences",
    "must_have.education"
]

for column in fields_to_inspect:
    example = df_all[
        df_all[column].apply(
            lambda x: isinstance(x, list) and len(x) > 0
        )
    ][["id", "headline", column]].iloc[0]

    print("\nFIELD:", column)
    print("Job ID:", example["id"])
    print("Headline:", example["headline"])
    print("Value:", example[column])

FIELD: must_have.languages
Job ID: 31549615
Headline: Kvalificerad Kontaktperson - Skyddsplaceringar
Value: [{'weight': 10, 'concept_id': 'zSLA_vw2_FXN', 'label': 'Svenska', 'legacy_ams_taxonomy_id': '502'}]

FIELD: must_have.work_experiences
Job ID: 31549595
Headline: 7 Steel Service Sweden AB söker Produktionsingenjör
Value: [{'weight': 10, 'concept_id': 'iJwC_kdU_cu7', 'label': 'Produktionsingenjör, maskin', 'legacy_ams_taxonomy_id': '6591'}]

FIELD: must_have.education
Job ID: 31549548
Headline: Universitetslektor i ryska
Value: [{'weight': 10, 'concept_id': 'y1vj_pmA_MPG', 'label': 'Humaniora', 'legacy_ams_taxonomy_id': '6'}]

In [ ]:
example = df_all[
    df_all["must_have.education_level"].apply(
        lambda x: isinstance(x, list) and len(x) > 0
    )
][["id", "headline", "must_have.education_level"]].iloc[0]

print("Job ID:", example["id"])
print("Headline:", example["headline"])
print("Education Level:", example["must_have.education_level"])

Job ID: 31549548
Headline: Universitetslektor i ryska
Education Level: [{'weight': 10, 'concept_id': 'SdS6_SLL_mRJ', 'label': 'Forskarutbildning', 'legacy_ams_taxonomy_id': '7'}]

In [ ]:
requirement_mapping = {
    "must_have": {
        "skills": "Skill",
        "languages": "Language",
        "work_experiences": "Work Experience",
        "education": "Education",
        "education_level": "Education Level"
    },
    "nice_to_have": {
        "skills": "Skill",
        "languages": "Language",
        "work_experiences": "Work Experience",
        "education": "Education",
        "education_level": "Education Level"
    }
}

requirements = []

for job in all_jobs:
    job_id = job["id"]

    for level, types in requirement_mapping.items():

        for source_field, requirement_type in types.items():

            values = job.get(level, {}).get(source_field, [])

            for value in values:
                requirements.append({
                    "job_id": job_id,
                    "concept_id": value.get("concept_id"),
                    "requirement_label": value.get("label"),
                    "requirement_type": requirement_type,
                    "requirement_level": (
                        "Must Have"
                        if level == "must_have"
                        else "Nice to Have"
                    ),
                    "weight": value.get("weight"),
                    "legacy_ams_taxonomy_id":
                        value.get("legacy_ams_taxonomy_id")
                })

df_requirements = pd.DataFrame(requirements)

print("Requirement rows:", len(df_requirements))
print("Jobs with structured requirements:",
      df_requirements["job_id"].nunique())

df_requirements.head(10)

Requirement rows: 327
Jobs with structured requirements: 171

,job_id,concept_id,requirement_label,requirement_type,requirement_level,weight,legacy_ams_taxonomy_id
0,31549656,rGGf_KLs_To7,Servitör/Servitris,Work Experience,Nice to Have,5.0,5487
1,31549654,zSLA_vw2_FXN,Svenska,Language,Nice to Have,5.0,502
2,31549654,NVxJ_hLg_TYS,Engelska,Language,Nice to Have,5.0,283
3,31549654,mLRm_6VG_s3c,Slovakiska,Language,Nice to Have,5.0,445
4,31549654,Gp9q_gTW_XAw,Polska,Language,Nice to Have,5.0,415
5,31549654,KF64_AvU_S4N,Städare,Work Experience,Nice to Have,5.0,None
6,31549661,XSBp_5wD_VaU,Restaurangchef,Work Experience,Nice to Have,5.0,5544
7,31549639,bXNH_MNX_dUR,"Sjuksköterska, grundutbildad",Work Experience,Nice to Have,5.0,7296
8,31549615,zSLA_vw2_FXN,Svenska,Language,Must Have,10.0,502
9,31549610,zSLA_vw2_FXN,Svenska,Language,Must Have,10.0,502

In [ ]:
duplicate_requirements = df_requirements.duplicated(
    subset=[
        "job_id",
        "concept_id",
        "requirement_type",
        "requirement_level"
    ]
).sum()

print("Total requirement rows:", len(df_requirements))
print("Duplicate requirement rows:", duplicate_requirements)
print(
    "Unique requirement combinations:",
    len(df_requirements) - duplicate_requirements
)

Total requirement rows: 327
Duplicate requirement rows: 0
Unique requirement combinations: 327

In [ ]:
# Save the main job-ad data
df_staging.to_csv(
    "job_ads_source.csv",
    index=False,
    encoding="utf-8-sig"
)

# Save the requirements data
df_requirements.to_csv(
    "job_requirements_source.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Files saved successfully.")
print("Job ads:", len(df_staging))
print("Requirements:", len(df_requirements))

Files saved successfully.
Job ads: 500
Requirements: 327